name: Node CI
on:
  push:
    branches:
      - trunk
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        node-version: [12, 14, 16]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Deduplicate packages
        if: ${{ matrix.node-version == '14' }}
        run: yarn dedupe --check
      - name: Cache /.yarn/cache
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
      - name: Check
        run: yarn tsc
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache /.yarn/cache
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
